In [10]:
# Bagged Decision Trees for Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
seed = 7

kfold = KFold(n_splits=10)
cart = DecisionTreeClassifier()
num_trees = 90
model = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.770745044429255


In [11]:
#building a predcting sysytem for bagging
import numpy as np
import pandas as pd
a=[6,93,50,30,64,28.7,0.356,23]
a=np.asarray(a)
a=a.reshape(1,-1)
model.fit(X,Y)
model.predict(a)

array([0.])

In [18]:
# Random Forest Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

X = array[:,0:8]
Y = array[:,8]

num_trees = 100
max_features = 3
kfold = KFold(n_splits=10)
model_random_forest = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model_random_forest, X, Y, cv=kfold)
print(results.mean())

0.7655673274094326


In [20]:
#building a prediction system for random tree
model_random_forest.fit(X,Y)
model_random_forest.predict(a)

array([0.])

In [21]:
# AdaBoost Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values

X = array[:,0:8]
Y = array[:,8]

num_trees = 31
seed=7
kfold = KFold(n_splits=10)
model_boost = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)
results = cross_val_score(model_boost, X, Y, cv=kfold)
print(results.mean())


0.7630724538619276


In [22]:
#predictive system for adaboost
model_boost.fit(X,Y)
model_boost.predict(a)

array([0.])

In [17]:
# Stacking Ensemble for Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
kfold = KFold(n_splits=10)

# create the sub models
estimators = []
model1 = LogisticRegression(max_iter=500)
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))

# create the ensemble model
ensemble = VotingClassifier(estimators)
results = cross_val_score(ensemble, X, Y, cv=kfold)
print(results.mean())

0.7630211893369788


In [26]:
#predictive system for stacking
ensemble.fit(X,Y)
ensemble.predict(a)

array([0.])